### ISSUE TITLE
Feature Request: Add support for additional commands.

### ISSUE THREAD

**Issue by toscano** [iloveicedgreentea/py-madvr#11]
Hey @iloveicedgreentea I love the new Home Assistant Integration. Nice work!

Could you find a way to support the following commands when you get a chance ?

 - `DisplayMessage`
 - `DisplayAudioVolume`
 - `DisplayAudioMute`
 - `CloseAudioMute`

Otherwise the integration is outstanding!

**Comment by iloveicedgreentea** [comment]
Thanks I can look into adding these

**Comment by iloveicedgreentea** [comment]
fixed in #19 

```
action: remote.send_command
data:
  command: DisplayMessage,3,test
target:
  entity_id: remote.madvr_envy

```
